### ISSUE TITLE
Alternative Download

### ISSUE THREAD

**Issue by IzzySoft** [unhappychoice/DroidFlyer#7]
Any chance to see an alternative download source for those not having/using Google Play? E.g. attaching the APK here to [Releases](https://github.com/unhappychoice/DroidFlyer/releases)?

**Comment by unhappychoice** [comment]
Sorry, there's no plan for that. :bow:

I think you can build this project by Android Studio by yourself.

**Comment by IzzySoft** [comment]
> Sorry, there's no plan for that.

Not the answer I hoped for – but of course, it's your project. What do you think about having your app included with [F-Droid](https://f-droid.org/)? F-Droid would build directly from your sources then.

> I think you can build this project by Android Studio by yourself.

I doubt that very much. I'm a user, not a dev. And I don't use Play Store.

**Comment by unhappychoice** [comment]
According to your repository https://github.com/IzzySoft/Adebar,  I don't know why you said your're  user.  You can just use Android SDK to build this application.

>  I don't use Play Store.

Even there're people don't Play Store, they can build by themselves. That's why this is open source application.

Thanks.

**Comment by unhappychoice** [comment]
And if you are not capable of understanding this application behavior, I don't recommend that you use this app.

Because, this app needs very sensitive API key to manipulate your bitFlyer account and I can mix code that empties your money if I want to do ( of course not.
So, think carefully please. 🙇

**Comment by IzzySoft** [comment]
According to the referenced repository, I can write Bash scripts, yes. And according to some others, also PHP and some Python. But I'm not an Android dev, and have no build environment at all.

But what I can accept is when you say that this is not an "end user's wallet" but rather something targeted at, how to say, very advanced "core coiner" – and I got the wrong impression from the Readme here (which was: "oh cool, a client for the Lightning network"). Apologies then – and a careful suggestion (no offense meant): Maybe the Readme could be a bit expanded, before the next one falls into this trap? :smiley:

Thanks, and all the best then!
